on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2    
    
      - name: Remove SNAPSHOT from pom.xml    
        run:  sed -i 's/-SNAPSHOT//g' pom.xml    
    
      - name: Setup Java 15    
        uses: actions/setup-java@v2    
        with:    
          distribution: 'adopt-hotspot'    
          java-version: '15'    
    
      - name: Build the release jar    
        run:  mvn package -Dmaven.test.skip=true    
    
      - name: Commit the released version    
        run: |    
          git config --local user.name  ${{ github.actor }}    
          git add pom.xml    
          VERSION=`sed -n '/version/,/version/p' pom.xml | head -1 | awk -F'[><]' '{print $3}'`
          git commit -am "Release version $VERSION - Updating the pom.xml"
          git push -f
          echo "v"$VERSION > version.txt

      - name: Create tag
        run: |
          ls
          cat version.txt | xargs git tag -a $1 -m "Version $1"
          git push --tags


